# Generated by Django 4.0.5 on 2022-06-28 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showmeat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meat',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meatcat', to='showmeat.category', verbose_name='دسته بندی'),
        ),
    ]
