# Generated by Django 4.0.5 on 2022-06-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showmeat', '0003_alter_category_options_alter_meat_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meat',
            name='added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان اضافه شدن به سیستم'),
        ),
        migrations.AlterField(
            model_name='meat',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان به روز رسانی'),
        ),
    ]
