# Generated by Django 4.0.5 on 2022-07-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showmeat', '0004_alter_meat_added_alter_meat_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='meat',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
