# Generated by Django 4.1 on 2022-08-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showmeat', '0005_meat_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='meat',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
