# Generated by Django 4.1 on 2022-08-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showmeat', '0006_meat_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meat',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد'),
        ),
    ]
