# Generated by Django 4.1 on 2022-08-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showmeat', '0007_alter_meat_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meat',
            name='quantity',
        ),
        migrations.AddField(
            model_name='meat',
            name='inventory',
            field=models.PositiveIntegerField(default=0, verbose_name='موجودی به کیلو'),
        ),
    ]
