# Generated by Django 4.1 on 2022-08-25 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showmeat', '0008_remove_meat_quantity_meat_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meat',
            name='inventory',
        ),
    ]
