# Generated by Django 4.1 on 2022-08-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showmeat', '0009_remove_meat_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='meat',
            name='inventory',
            field=models.PositiveIntegerField(default=0, verbose_name='موجودی به کیلو'),
        ),
    ]
