# Generated by Django 4.1 on 2022-08-14 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_shippingaddress_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='dated_added',
            new_name='date_added',
        ),
    ]
