# Generated by Django 3.2.15 on 2022-09-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_alter_shippingaddress_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
