# Generated by Django 3.2.15 on 2022-09-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_shippingaddress_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='selected',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='آدرس منتخب'),
        ),
    ]
