# Generated by Django 3.1 on 2022-09-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_deliverytimemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytimemodel',
            name='day',
            field=models.DateField(default=('1401', 'شهریور', '21'), verbose_name='روز ارسال'),
        ),
        migrations.AlterField(
            model_name='deliverytimemodel',
            name='flags',
            field=models.CharField(default=('1401', 'شهریور', 22), max_length=30, verbose_name='فردا'),
        ),
    ]
