# Generated by Django 3.2.15 on 2022-09-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_auto_20220912_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default=0, max_length=30, verbose_name='نحوه پرداخت'),
        ),
    ]
