# Generated by Django 3.2.15 on 2022-09-14 10:56

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0019_auto_20220912_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytimemodel',
            name='day',
            field=django_jalali.db.models.jDateField(default=datetime.date(2022, 9, 14), max_length=30, verbose_name='روز ارسال'),
        ),
        migrations.AlterField(
            model_name='deliverytimemodel',
            name='flags',
            field=django_jalali.db.models.jDateField(default=datetime.date(2022, 9, 15), max_length=30, verbose_name='فردا'),
        ),
    ]
