# Generated by Django 3.2.15 on 2022-09-25 18:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0020_auto_20220914_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytimemodel',
            name='day',
            field=django_jalali.db.models.jDateField(default=datetime.date(2022, 9, 25), max_length=30, verbose_name='روز ارسال'),
        ),
        migrations.AlterField(
            model_name='deliverytimemodel',
            name='flags',
            field=django_jalali.db.models.jDateField(default=datetime.date(2022, 9, 26), max_length=30, verbose_name='فردا'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, max_length=30, verbose_name='زمان ثبت سفارش'),
        ),
        migrations.CreateModel(
            name='OrderItemHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=50, null=True, verbose_name='محصول انتخاب شده')),
                ('quantity', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderhistory', to='cart.order', verbose_name='سفارش مربوطه')),
            ],
            options={
                'verbose_name': 'آیتم سفارش داده شده',
                'verbose_name_plural': 'اقلام سفارش داده شده',
            },
        ),
    ]
