# Generated by Django 3.2.15 on 2022-09-29 13:48

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0021_auto_20220925_2138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitemhistory',
            options={'verbose_name': 'تاریخچه محصول سفارش داده شده', 'verbose_name_plural': 'تاریخچه محصولات سفارش داده شده'},
        ),
        migrations.AddField(
            model_name='orderitemhistory',
            name='address',
            field=models.CharField(default=0, max_length=300, verbose_name='آدرس ارسال شذه'),
        ),
        migrations.AddField(
            model_name='orderitemhistory',
            name='delivery_day',
            field=models.CharField(default=0, max_length=30, verbose_name='روز ارسال'),
        ),
        migrations.AddField(
            model_name='orderitemhistory',
            name='delivery_time',
            field=models.CharField(default=0, max_length=30, verbose_name='زمان ارسال'),
        ),
        migrations.AlterField(
            model_name='deliverytimemodel',
            name='day',
            field=django_jalali.db.models.jDateField(default=datetime.date(2022, 9, 29), max_length=30, verbose_name='روز ارسال'),
        ),
        migrations.AlterField(
            model_name='deliverytimemodel',
            name='flags',
            field=django_jalali.db.models.jDateField(default=datetime.date(2022, 9, 30), max_length=30, verbose_name='فردا'),
        ),
    ]
