# Generated by Django 3.2.15 on 2022-09-29 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0022_auto_20220929_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitemhistory',
            name='delivery_day',
        ),
    ]
