# Generated by Django 3.2.15 on 2022-09-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0024_rename_delivery_time_order_delivery_time_bound'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_time_bound',
            new_name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='orderitemhistory',
            name='delivery_time',
        ),
        migrations.AddField(
            model_name='orderitemhistory',
            name='delivery_time_bound',
            field=models.CharField(default=0, max_length=30, verbose_name='بازه ی زمانی ارسال'),
        ),
    ]
