# Generated by Django 3.2.15 on 2022-09-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0025_auto_20220929_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='online_method',
            field=models.BooleanField(default=False, verbose_name='پرداخت آنلاین'),
        ),
    ]
