# Generated by Django 3.2.15 on 2022-10-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0030_auto_20221011_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitemhistory',
            name='weight',
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default='tfh730nijpgbnmc', max_length=50, verbose_name='شماره پیگیری'),
        ),
    ]
