# Generated by Django 3.2.15 on 2022-10-15 12:05

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0032_auto_20221011_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sent',
            field=models.BooleanField(default=False, verbose_name='ارسال شده؟'),
        ),
        migrations.AlterField(
            model_name='deliverytimemodel',
            name='day',
            field=django_jalali.db.models.jDateField(default=datetime.date(2022, 10, 15), max_length=30, verbose_name='روز ارسال'),
        ),
        migrations.AlterField(
            model_name='deliverytimemodel',
            name='flags',
            field=django_jalali.db.models.jDateField(default=datetime.date(2022, 10, 16), max_length=30, verbose_name='فردا'),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default='houbrr6kwy5nm6w', max_length=50, verbose_name='شماره پیگیری'),
        ),
    ]
