# Generated by Django 3.2.15 on 2022-11-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0035_auto_20221101_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default=0, max_length=50, verbose_name='شماره پیگیری'),
        ),
    ]
