# Generated by Django 3.2.18 on 2023-05-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0038_auto_20230511_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='date_added',
            field=models.DateField(default=('21 اردیبهشت 1402', '1402', 'اردیبهشت', '21'), verbose_name='تاریخ ثبت'),
        ),
    ]
