# Generated by Django 3.2.18 on 2023-05-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0039_alter_orderitem_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='date_added',
            field=models.DateField(default='21 اردیبهشت 1402 ساعت 19:27', verbose_name='تاریخ ثبت'),
        ),
    ]
