# Generated by Django 3.2.18 on 2023-05-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0040_alter_orderitem_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='orderitemhistory',
            name='addedtime',
            field=models.DateField(default=('21 اردیبهشت 1402', '1402', 'اردیبهشت', '21'), verbose_name='تاریخ ثبت سفارش'),
        ),
    ]
