# Generated by Django 3.2.18 on 2023-05-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0041_auto_20230511_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemhistory',
            name='addedtime',
            field=models.CharField(default=('21 اردیبهشت 1402', '1402', 'اردیبهشت', '21'), max_length=20, verbose_name='تاریخ ثبت سفارش'),
        ),
    ]
